version: '3'

services:
  togo-postgresql:
    image: postgres:13.2-alpine
    container_name: togo-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=togo
      - POSTGRES_PASSWORD=togo
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always